name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "docs/**"

jobs:
  tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["7.3", "7.4", "8.0"]
        phpunit-versions: ["latest"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=60
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist ${{ matrix.composer-extra-arguments }}

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite=unit

  static-analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs
